package com.jw.springbootbegin.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.initiator
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    private Long initiator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.receiver
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.content-id
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    private Long contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.status
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.initiator
     *
     * @return the value of notification.initiator
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public Long getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.initiator
     *
     * @param initiator the value for notification.initiator
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public void setInitiator(Long initiator) {
        this.initiator = initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.receiver
     *
     * @return the value of notification.receiver
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.receiver
     *
     * @param receiver the value for notification.receiver
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.content-id
     *
     * @return the value of notification.content-id
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.content-id
     *
     * @param contentId the value for notification.content-id
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type
     *
     * @return the value of notification.type
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type
     *
     * @param type the value for notification.type
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.status
     *
     * @return the value of notification.status
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.status
     *
     * @param status the value for notification.status
     *
     * @mbg.generated Tue Mar 03 21:47:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}